name: Push to Phraseapp

on:
  workflow_run:
    workflows: ["CI Tests"]
    branches: [main]
    types:
      - completed

env:
  PHRASEAPP_CLI_VERSION: "2.2.0"

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Phrase CLI
        uses: winify-ag/setup-phraseapp@v2
        with:
          version: ${{ env.PHRASEAPP_CLI_VERSION }}
      - name: Push translation to Phrase.com
        run:
          phrase push --access_token ${{ secrets.PHRASE_APP_ACCESS_TOKEN }}
